[package]
name = "selfie-enrollment-e2e"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
axum.workspace = true
clap.workspace = true
hex.workspace = true
p256.workspace = true
rand.workspace = true
selfie-enrollment-api-types.workspace = true
selfie-enrollment-client.workspace = true
selfie-enrollment-sealed-types.workspace = true
serde_json.workspace = true
tempfile.workspace = true
tokio = { workspace = true, features = ["fs"] }
zeroize.workspace = true
