[package]
name = "di-migration-enclave"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "di-migration-enclave"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
di-migration-enclave-types.workspace = true
hex.workspace = true
pontifex = { workspace = true, features = ["channel", "nsm", "server"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "sync", "time"] }
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
