[package]
name = "migration-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
attested-request = "0.1.1"
aws-config.workspace = true
clap = { workspace = true, features = ["derive", "env"] }
aws-sdk-dynamodb.workspace = true
aws-sdk-kms.workspace = true
aws-sdk-s3.workspace = true
async-trait.workspace = true
axum.workspace = true
base64.workspace = true
fastrand.workspace = true
p256.workspace = true
proof.workspace = true
reqwest = { workspace = true, features = ["json"] }
serde = { workspace = true }
serde_json.workspace = true
telemetry-batteries = { workspace = true, features = ["axum"] }
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
di-migration-primitives.workspace = true
di-migration-storage.workspace = true

[dev-dependencies]
attested-request = { version = "0.1.1", features = ["test-util"] }
http-body-util.workspace = true
di-migration-client.workspace = true
tower.workspace = true
